### ISSUE TITLE
Compare to imagemeta?

### ISSUE THREAD

**Issue by mholt** [soypat/exif#1]
Hi -- I just found this repo and since it's focused on performance, I was wondering if you could add a benchmark comparing [imagemeta](https://github.com/evanoberholster/imagemeta) as well. (I'm traveling currently or I'd just do it myself, but I'm also not familiar with your API yet.)

I know that lib is also under active development, so maybe there's room to share ideas and even consolidate if that would make sense.

**Comment by soypat** [comment]
Quite faster (x3) though it seems it is much more limited in what it can parse. I'll go ahead and talk to them to see if there's room for consolidation.
```
BenchmarkImageMeta_SmallImage-12      	  299059	      3823 ns/op	     921 B/op	       5 allocs/op
BenchmarkImageMeta_LargeImage-12      	  357704	      3400 ns/op	     929 B/op	       6 allocs/op
```
